[package]
name = "rs-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
csv = "1.3.1"
serde = { version = "1.0.216", features = ["derive"] }
anyhow = "1.0.95"
serde_json = "1.0.134"
serde_yaml = "0.9.34"
rand = "0.8.5"
base64 = "0.22.1"
